cc_library(
    name="page_featurizer",
    srcs=[
        "page_featurizer.cc",
    ],
    hdrs=[
        "page_featurizer.h",
    ],
    deps=[
        "//common:page",
        "@tokme//:tokme",
    ],
    visibility = ["//visibility:public"],
)
